// const products = [
//     {
//         img: "./images/tomato.svg",
//         title: "Tomato",
//         weight: "$25/KG",
//         text: "It is a long established fact that a reader will be distracted by.",
//         link: "SHOP NOW",
//     },
//     {
//         img: "./images/meat.svg",
//         title: "Meat",
//         weight: "$25/KG",
//         text: "It is a long established fact that a reader will be distracted by.",
//         link: "SHOP NOW",
//     },
//     {
//         img: "./images/potato.png",
//         title: "Potato",
//         weight: "$25/KG",
//         text: "It is a long established fact that a reader will be distracted by.",
//         link: "SHOP NOW",
//     },
//     {
//         img: "./images/cauliflower.png",
//         title: "Cauliflower",
//         weight: "$25/KG",
//         text: "It is a long established fact that a reader will be distracted by.",
//         link: "SHOP NOW",
//     },
//     {
//         img: "./images/cucmber.svg",
//         title: "Cucumber",
//         weight: "$25/KG",
//         text: "It is a long established fact that a reader will be distracted by.",
//         link: "SHOP NOW",
//     },
//     {
//         img: "./images/banana.svg",
//         title: "Banana",
//         weight: "$25/KG",
//         text: "It is a long established fact that a reader will be distracted by.",
//         link: "SHOP NOW",
//     },
//     {
//         img: "./images/onion.svg",
//         title: "Onion",
//         weight: "$25/KG",
//         text: "It is a long established fact that a reader will be distracted by.",
//         link: "SHOP NOW",
//     },
//     {
//         img: "./images/chhola.png",
//         title: "Chhola",
//         weight: "$25/KG",
//         text: "It is a long established fact that a reader will be distracted by.",
//         link: "SHOP NOW",
//     },
// ];